In [1]:
from imutils import face_utils
import dlib
import cv2
import numpy as np
from PIL import Image
import os
import pandas as pd
from sklearn.preprocessing import LabelBinarizer
import tensorflow as tf

In [8]:
#!pip install imutils --user
#!pip install opencv-python==3.3.0.9 --user
#!pip install PILLOW --user


In [2]:
p = "shape_predictor_68_face_landmarks.dat"
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor(p)

In [3]:
caminhos = [os.path.join('fotos/all', f) for f in os.listdir('fotos/all')]
faces = []
ids = []


In [4]:
for caminhoImagem in caminhos:
    indice = 0
    imagemFace = cv2.cvtColor(cv2.imread(caminhoImagem), cv2.COLOR_BGR2GRAY)
    # Get faces into image
    rects = detector(imagemFace, 0)
    # For each detected face, find the landmark.
    for (i, rect) in enumerate(rects):
        # Make the prediction and transfom it to numpy array
        shape = predictor(imagemFace, rect)
        shape = face_utils.shape_to_np(shape)
        id1 = os.path.split(caminhoImagem)[-1].split('-')[1]
        id2 = int(os.path.split(id1)[-1].split('_')[0])
        #df.set_value( indice, 'foto', shape) 
        #df.set_value( indice, 'sentimento', id2)
        #indice = indice +1
        ids.append(id2)
        faces.append(shape.reshape(-1))

In [12]:

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [36]:
#ids
faces[0]

array([241, 260, 244, 282, 249, 303, 254, 324, 261, 343, 273, 360, 290,
       372, 306, 383, 325, 387, 343, 382, 359, 371, 375, 357, 387, 339,
       393, 319, 396, 298, 400, 278, 401, 256, 254, 235, 261, 224, 274,
       216, 289, 216, 302, 222, 339, 222, 352, 215, 367, 215, 380, 222,
       388, 233, 321, 244, 322, 260, 322, 275, 323, 290, 306, 298, 315,
       301, 323, 304, 332, 301, 340, 297, 272, 252, 281, 245, 291, 244,
       302, 251, 292, 252, 281, 253, 341, 250, 352, 243, 362, 243, 371,
       250, 362, 252, 351, 251, 283, 319, 298, 315, 312, 314, 323, 315,
       333, 314, 347, 314, 362, 317, 348, 333, 334, 340, 323, 342, 312,
       341, 298, 335, 288, 320, 313, 320, 323, 321, 333, 320, 357, 319,
       333, 332, 323, 333, 312, 333])

In [13]:
vectorizer = CountVectorizer()
le = LabelEncoder()

In [14]:
X = faces
y = le.fit_transform(ids)

In [15]:
y

array([1, 2, 3, 4, 0, 0, 1, 1, 1, 4, 0, 3, 4, 2, 3, 3, 2, 0, 4, 4, 1, 2,
       0, 4, 3, 2, 2, 0, 1, 3, 0, 2, 3, 1, 0, 2, 0, 4, 4, 4, 4, 3, 1, 3,
       0, 1, 4, 0, 4, 1, 3, 2, 2, 0, 3, 1, 4, 4, 1, 2, 1, 0, 3, 1, 3, 4,
       2, 4, 0, 4, 0, 0, 0, 2, 1, 2, 4, 2, 2, 1, 0, 1, 3, 4, 3, 2, 1, 1,
       3, 3, 0, 1, 3, 2, 2, 2, 0, 3, 4, 3, 0, 2, 3, 2, 1, 3, 1, 4, 4, 4,
       0, 1, 0, 2, 0, 3, 3, 4, 2, 4, 4, 0, 3, 2, 3, 1, 2, 1, 1, 0])

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [19]:
#print(X_train)
#print(y_train)
#print(X_test)

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier

In [21]:
clf = OneVsRestClassifier(LogisticRegression())

In [22]:
clf.fit(X_train, y_train)

/usr/local/lib64/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib64/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib64/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib64/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib64/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warnin

OneVsRestClassifier(estimator=LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='warn',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='warn', tol=0.0001,
                                                 verbose=0, warm_start=False),
                    n_jobs=None)

In [23]:
print(clf.score(X_test, y_test))

0.5769230769230769


In [24]:
y_pred = clf.predict(X_test)

In [25]:
y_pred

array([1, 3, 4, 2, 3, 4, 4, 3, 1, 1, 2, 2, 3, 0, 3, 2, 0, 2, 2, 1, 4, 2,
       3, 0, 1, 3])

In [27]:
import numpy
from sklearn.model_selection import cross_val_score, KFold
from sklearn.metrics import classification_report

In [28]:
kf = KFold(n_splits=5, shuffle=True)

scores = cross_val_score(clf, X, y, cv=kf)

print(scores)
print(numpy.mean(scores))

/usr/local/lib64/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib64/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib64/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib64/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib64/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warnin

[0.57692308 0.69230769 0.57692308 0.65384615 0.38461538]
0.5769230769230769


/usr/local/lib64/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib64/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib64/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib64/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib64/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warnin

In [30]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.67      0.33      0.44         6
           1       0.40      0.67      0.50         3
           2       0.43      0.60      0.50         5
           3       0.57      0.67      0.62         6
           4       1.00      0.67      0.80         6

    accuracy                           0.58        26
   macro avg       0.61      0.59      0.57        26
weighted avg       0.65      0.58      0.58        26



In [32]:
from joblib import dump, load
dump(clf, 'LogReg_BBFace.joblib') 

['LogReg_BBFace.joblib']